### ISSUE TITLE
Sveltekit breaking changes

### ISSUE THREAD

**Issue by murunwas** [Refzlund/sveltekit-zero-api#1]
To access the `request ` body use the text/json/arrayBuffer/formData methods, e.g. `body = await request.json()`. See https://github.com/sveltejs/kit/pull/3384 for details: see example below:

```javascript
export async function post({ request }) {
	const body= await request.json();
	return respond(body);
}
```

**Comment by Refzlund** [comment]
Thanks for the heads-up. From 0.9.2, the parameters of the end-point functions are now given a generic interface that implements the related interface i.e.

```ts
interface Post {
    body: {
        a: string,
        b: number
    }
}

export async function post({ request ]: API<Post>) {
    const body = request.json()
    
    // OK
    let someString = body.a
}
```

And replace any `QueryGet<T>` with `API<T>`

Pardon the late response. I've just settled into to a new place.

If you have any ideas in how-to make formData more available in Typescript I'll be glad to hear it. Happy coding

**Comment by murunwas** [comment]
`Backend`
![image](https://user-images.githubusercontent.com/8838943/152683032-c775c102-5c76-4514-ba88-d7d04233bad5.png)

`Frontend`
there's no `body` on post method.

![image](https://user-images.githubusercontent.com/8838943/152682966-8a762466-6bec-44ab-8a9d-572ef8c658a0.png)

**Comment by Refzlund** [comment]
Whoops. I'll push a fix ASAP — within this hour

**Comment by Refzlund** [comment]
`npm i sveltekit-zero-api@0.9.2-b`

And it should be a-okay again🤞 Thank you for letting me know about the issue

**Comment by hmiiro** [comment]
> `npm i sveltekit-zero-api@0.9.2-b`
> 
> And it should be a-okay again🤞 Thank you for letting me know about the issue

This fixed the issue well! Thanks!
