### ISSUE TITLE
./sveltekit-zero-api file doesn't exist

### ISSUE THREAD

**Issue by sharmapukar217** [Refzlund/sveltekit-zero-api#13]
The file `./sveltekit-zero-api` file imported on api.ts file doesn't exist

**Comment by Refzlund** [comment]
Hey! Sorry for the late reply.

`sveltekit-zero-api.d.ts` from `import type { GeneratedAPI } from './sveltekit-zero-api.d.ts'` should be generated when you run the project.

So
1. `npm i -D sveltekit-zero-api`
2. Add **sveltekit-zero-api** to your project inside your vite config.
3. `npm run dev`
4. `src/api.ts` and `.svelte-kit/types/src/sveltekit-zero-api.d.ts` should be generated.

However I have noted that SvelteKit tends to delete files from their `.svelte-kit/types`.

I will move the generated file next to the generated `api.ts` and push an update. Thanks for the feedback, I'll close the comment when I commit the push

**Comment by Refzlund** [comment]
Should be fixed via latest commit
https://github.com/Refzlund/sveltekit-zero-api/commit/2daa46db519ed00eb9bb3e2e726c663bc4f2b8ab#diff-9d3dcddfc8a4d54323d30493fb8d63b3073f9c1ae87fe6bc4fba18dbefb52304R48

Wait for sveltekit-zero-api@0.13.0
