### ISSUE TITLE
When passing fetch to an api POST call, an error is raised (Failed to get response header "content-type")

### ISSUE THREAD

**Issue by Bewinxed** [Refzlund/sveltekit-zero-api#16]
When I pass a function like this

```
export async function getMultipleNftRoyaltyStatus(
	fetch,
	nftAddresses: string[],
	nftRoyaltyCache: Writable<{ [key: string]: RoyaltyStatus }>
) {

	// console.log("I'm being called for nftAddresses", nftAddresses);
    const response = await api.royalty.POST({body: {nftAddresses: nftAddresses}, headers: {
        'Content-Type': 'application/json',
    }}, fetch).$.Ok(res => res.body)
```

The following error gets raised in console:
```
This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
Error: Failed to get response header "content-type" — it must be included by the `filterSerializedResponseHeaders` option: https://kit.svelte.dev/docs/hooks#server-hooks-handle (at /royalty/[guild_id])
    at Headers.response.headers.get (/node_modules/@sveltejs/kit/src/runtime/server/page/load_data.js:311:13)
    at eval (/node_modules/sveltekit-zero-api/dist/api/handler.js:64:35)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Refzlund** [comment]
@Bewinxed I believe SvelteKit only accepts lower-case headers, so I would guess it's a capitalization issue;
```ts
const response = await api.royalty.POST({body: {nftAddresses: nftAddresses}, headers: {
    'content-type': 'application/json',
}}, fetch).$.Ok(res => res.body)
```

However... the API automatically adds `content-type` also if it wasn't provided, so quite a mystical error really🤔

Try lower-case capitalization if that works then that's that🤷

**Comment by Bewinxed** [comment]
> @Bewinxed I believe SvelteKit only accepts lower-case headers, so I would guess it's a capitalization issue;
> 
> ```ts
> const response = await api.royalty.POST({body: {nftAddresses: nftAddresses}, headers: {
>     'content-type': 'application/json',
> }}, fetch).$.Ok(res => res.body)
> ```
> 
> However... the API automatically adds `content-type` also if it wasn't provided, so quite a mystical error really🤔
> 
> Try lower-case capitalization if that works then that's that🤷

I actually only added that header thinking it would fix it, but even without that header, same issue.

**Comment by Refzlund** [comment]
@Bewinxed I can't seem to reproduce it. 

Can you please try to reproduce it in a new project and if it occurs send me link me so I can clone and test on it?

**Comment by Refzlund** [comment]
Closing this as I am missing feedback
