### ISSUE TITLE
Did something change? Module '"sveltekit-zero-api/http"' has no exported member 'Ok'.

### ISSUE THREAD

**Issue by Bewinxed** [Refzlund/sveltekit-zero-api#18]
Suddenly got this error, did something change?

Also how do we define GET endpoints using this?

Thanks!

**Comment by Refzlund** [comment]
Hey there! Shouldn't be the case. I just tested it in a clean project with the latest version of the package, and everything works as expected.

----

Before svelte-package@2.0.0 I was dealing with packaging a bit different, and migrating to version 2 simplified a lot of things for the publishing process of the package.

The package was updated to include
```ts
	"files": [
		"dist"
	],
	"main": "dist/index.js",
	"exports": {
		".": "./dist/index.js",
		"./http": "./dist/http.js",
		"./api": "./dist/api/index.js",
		"./z": "./dist/z.js",
		"./helpers": "./dist/helpers.js"
	},
	"typesVersions": {
		"*": {
			"http": [
				"dist/http.d.ts"
			],
			"api": [
				"dist/api/index.d.ts"
			],
			"z": [
				"dist/z.d.ts"
			],
			"helpers": [
				"dist/helpers.d.ts"
			]
		}
	},

```

Where `typesVersions` were required to satisfy TypeScript - as Typescript does not infer the exports by itself. Had to fiddle with it for a little bit, but it worked in the end.

From my experience TypeScript can be a bit funky with certain configurations, and I can't really pinpoint why it isn't working for you. Try disabling extensions in your IDE unrelated to Svelte/Kit. Perhaps look at your settings in the IDE related to TypeScript.

**Comment by Refzlund** [comment]
I may or may not change some structure for the project by utilizing [refzlund/giraffe](https://github.com/Refzlund/giraffe) — a template I created to improve the open-source experience as collaborative developers.

I assume the problem here has been resolved - otherwise I am just informing you changes to the issues you're experience are expected as of 2.0.0🦒
