### ISSUE TITLE
Escape filename special characters

### ISSUE THREAD

**Issue by kauderk** [Refzlund/sveltekit-zero-api#7]
Paths with " " white spaces or any other special character will generate invalid types at
  - project\\.svelte-kit\types\src\sveltekit-zero-api.d.ts

To fix this:
- project\node_modules\sveltekit-zero-api\utils\string.js > invalidCharacters (array)
  - Add " " white space

Alternative: use npm patch
`project\patches\sveltekit-zero-api+0.11.15.patch`
```
diff --git a/node_modules/sveltekit-zero-api/utils/string.js b/node_modules/sveltekit-zero-api/utils/string.js
index 41d8586..d3e61f4 100644
--- a/node_modules/sveltekit-zero-api/utils/string.js
+++ b/node_modules/sveltekit-zero-api/utils/string.js
@@ -1,4 +1,4 @@
-const invalidCharacters = ['[', '/', '\\', ']', '-', ':', '.', '+', '(', ')'];
+const invalidCharacters = ['[', '/', '\\', ']', '-', ':', '.', '+', '(', ')', ' '];
 /** Replaces `[` `/` `\` `]` `-` `:` `.` with `_` */
 export const toValidVariable = (name = '') => name.replaceAll(new RegExp(invalidCharacters.map(m => '\\' + m).join('|'), 'g'), '_');
 /** When importing files: We don't add `.ts` in the import-statement */
```

**Comment by Refzlund** [comment]
> Paths with " " white spaces or any other special character will generate invalid types at
> 
> * project\.svelte-kit\types\src\sveltekit-zero-api.d.ts
> 
> To fix this:
> 
> * project\node_modules\sveltekit-zero-api\utils\string.js > invalidCharacters (array)
>   
>   * Add " " white space
> 
> Alternative: use npm patch `project\patches\sveltekit-zero-api+0.11.15.patch`
> 
> ```
> diff --git a/node_modules/sveltekit-zero-api/utils/string.js b/node_modules/sveltekit-zero-api/utils/string.js
> index 41d8586..d3e61f4 100644
> --- a/node_modules/sveltekit-zero-api/utils/string.js
> +++ b/node_modules/sveltekit-zero-api/utils/string.js
> @@ -1,4 +1,4 @@
> -const invalidCharacters = ['[', '/', '\\', ']', '-', ':', '.', '+', '(', ')'];
> +const invalidCharacters = ['[', '/', '\\', ']', '-', ':', '.', '+', '(', ')', ' '];
>  /** Replaces `[` `/` `\` `]` `-` `:` `.` with `_` */
>  export const toValidVariable = (name = '') => name.replaceAll(new RegExp(invalidCharacters.map(m => '\\' + m).join('|'), 'g'), '_');
>  /** When importing files: We don't add `.ts` in the import-statement */
> ```

Thank you! https://github.com/Refzlund/sveltekit-zero-api/commit/e4ca03619c21667dd6e589ecf13b15883e1d6771
