### ISSUE TITLE
MAJOR: Account for param types in sveltekit-zero-api.d.ts creation

### ISSUE THREAD

**Issue by mavthedev** [Refzlund/sveltekit-zero-api#9]
If your param has a type checker with it and then your route would be something like this `blog/[slug=slug]`
But this causes issues when generating type files because you then get code that looks like this `slug=slug$: (slug=slug: S) => {}` which is invalid

**Comment by Refzlund** [comment]
Sorry for the late reply, and thank you for putting it in my radar🦒

**Comment by mavthedev** [comment]
yw
